const templates: { [key: string]: string } = {
    '\/etc\/module\.xml$': require('../templates/etc/module.xml'),
    'di\.xml$': require('../templates/etc/di.xml'),
    'acl\.xml$': require('../templates/etc/acl.xml'),
    '\/etc\/crontab\.xml$': require('../templates/etc/crontab.xml'),
    '\/etc\/cron_groups\.xml$': require('../templates/etc/cron_groups.xml'),
    '\/etc\/db_schema\.xml$': require('../templates/etc/db_schema.xml'),
    '\/etc\/webapi\.xml$': require('../templates/etc/webapi.xml'),
    '\/etc\/((frontend|adminhtml)\/)?routes\.xml$': require('../templates/etc/routes.xml'),
    '\/etc\/((frontend|adminhtml)\/)?events\.xml$': require('../templates/etc/events.xml'),
    '\/etc\/((frontend|adminhtml)\/)?config\.xml$': require('../templates/etc/config.xml'),
    '\/etc\/frontend\/sections\.xml$': require('../templates/etc/sections.xml'),
    '\/etc\/(adminhtml\/)?system\.xml$': require('../templates/etc/system.xml'),
    '\/etc\/(adminhtml\/)?catalog_attributes\.xml$': require('../templates/etc/catalog_attributes.xml'),
    '\/etc\/(adminhtml\/)?menu\.xml$': require('../templates/etc/menu.xml'),
    '\/view\/(frontend|adminhtml)\/layout\/.*\.xml$': require('../templates/layout.xml'),
    '\/Block\/.*\.php$': require('../templates/block.php'),
    '\/Controller\/Adminhtml\/.*\.php$': require('../templates/controller_backend.php'),
    '\/Controller\/.*\.php$': require('../templates/controller.php'),
    '\/Model\/ResourceModel\/.*\/Collection\.php$': require('../templates/resource_collection_model.php'),
    '\/Model\/ResourceModel\/.*\.php$': require('../templates/resource_model.php'),
    '\/Model\/.*\.php$': require('../templates/model.php'),
    '\/Observer\/.*\.php$': require('../templates/observer.php'),
    '\/Console\/.*\.php$': require('../templates/command.php'),
    '\/Setup\/InstallData.php$': require('../templates/Setup/InstallData.php'),
    '\/Setup\/InstallSchema.php$': require('../templates/Setup/InstallSchema.php'),
    '\/Setup\/Recurring.php$': require('../templates/Setup/Recurring.php'),
    '\/Setup\/UpgradeData.php$': require('../templates/Setup/UpgradeData.php'),
    '\/Setup\/UpgradeSchema.php$': require('../templates/Setup/UpgradeSchema.php'),
    '.php$': require('../templates/class.php'),
};

export default templates;